apiVersion: v1
kind: Service
metadata:
  name: my-blue-green-app-service
  labels:
    app: my-app
spec:
<<<<<<< HEAD
  type: "LoadBalancer"
=======
  type: LoadBalancer
>>>>>>> bfa8fc177e20f02aecec0094803f32d04854e08a
  ports:
  - name: http
    port: 80
    targetPort: 8080

  # Note here that we match both the app and the version
  selector:
    app: green-app