apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
<<<<<<< HEAD
=======
  type: ClusterIP
>>>>>>> bfa8fc177e20f02aecec0094803f32d04854e08a
  ports:
  - name: http
    port: 80
    targetPort: http
  selector:
    app: my-app
